version: '3'
services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: python3 /app/yandex_eco_fest_bot/main.py

  postgres:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"  # todo: change port
    restart: on-failure
    volumes:
      - redis_data:/data

volumes:
  redis_data: