from aiogram.fsm.state import State

WAITING_FOR_PICTURE_SUBMISSION = State("WAITING_FOR_PICTURE_SUBMISSION")
WAITING_FOR_TEXT_SUBMISSION = State("WAITING_FOR_TEXT_SUBMISSION")
WAITING_FOR_VOICE_SUBMISSION = State("WAITING_FOR_VOICE_SUBMISSION")
WAITING_FOR_VIDEO_SUBMISSION = State("WAITING_FOR_VIDEO_SUBMISSION")
WAITING_FOR_VERIFICATION_CODE_SUBMISSION = State("WAITING_FOR_VERIFICATION_CODE_SUBMISSION")
